[package]
name = "allsorts-tools"
version = "0.1.0"
authors = ["YesLogic Pty. Ltd. <info@yeslogic.com>"]
edition = "2018"

[[bin]]
name = "allsorts"
path = "src/main.rs"

[dependencies]
allsorts = { git = "ssh://git@github.com/yeslogic/allsorts.git" }
atty = "0.2"
encoding_rs = "0.8.16"
getopts = "0.2"
gumdrop = "0.7.0"
itertools = "0.8"
